languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Steven Lio"
# copyright = "Copy, _right?_ :thinking_face:"
copyright = "© 2024 Steven Lio"

[params]
  dateFormat = "02 Jan, 2006"

  mainSections = ["section1", "section2"]
  description = "Personal site of Steven Lio"

[params.author]
  name = "Steven Lio"
  image = "img/android-chrome-512x512.png"
  headline = "Data Scientist | Machine Learning Engineer | Data Analyst"
  bio = "Data Scientist | Machine Learning Engineer | Data Analyst"
  links = [
    { linkedin = "https://linkedin.com/in/steven-lio" },
	{ github = "https://github.com/stevenlio88" },
	{ medium = "https://stevenlio.medium.com/" },
	{ instagram = "https://www.instagram.com/stevenlio/" },
	{ flickr = "https://www.flickr.com/photos/stevenlio/" },
	# { email = "mailto:hello@your_domain.com" },
    # { link = "https://link-to-some-website.com/" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { blogger = "https://username.blogspot.com/" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { foursquare = "https://foursquare.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { google-scholar = "https://scholar.google.com/citations?user=user-id" },
    # { hashnode = "https://username.hashnode.dev" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { mendeley = "https://www.mendeley.com/" },
    # { microsoft = "https://www.microsoft.com/" },
    # { orcid = "https://orcid.org/userid" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { researchgate = "https://www.researchgate.net/profile/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { x-twitter = "https://twitter.com/username" },
    # { youtube = "https://youtube.com/username" }
  ]
